import { test, expect } from '@playwright/test'
test('teclado fecha onboarding, opera filtro, abre detalhe e restaura foco', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const filter = page.getByLabel('O que você quer descartar?')
  await filter.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(filter).toHaveValue('batteries')
  // Uma localidade com um único destino mantém a cadeia de foco previsível.
  await page.getByLabel('Localidade', { exact: true }).selectOption('Belo Jardim')
  const card = page.getByRole('list', { name: 'Destinos de descarte' }).getByRole('button').first()
  await card.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Drogasil, Belo Jardim' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: /Recicla Pilhas/ })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: /Como chegar/ })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(card).toBeFocused()
})
test('layout conserva filtro, área de mapa e painel operável', async ({ page, isMobile }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Continuar sem localização' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const filter = await page.getByLabel('O que você quer descartar?').boundingBox()
  const panel = await page.locator('#points-panel').boundingBox()
  expect(filter!.height).toBeGreaterThanOrEqual(44)
  expect(panel!.width).toBeGreaterThan(250)
  if (isMobile) {
    expect(panel!.y - (filter!.y + filter!.height)).toBeGreaterThan(120)
    await page.getByRole('button', { name: 'Ampliar lista' }).click()
    await expect(page.getByRole('button', { name: 'Recolher lista' })).toHaveAttribute('aria-expanded', 'true')
  }
  const last = page.locator('.point-list li').last()
  const lastName = await last.locator('strong').textContent()
  await last.locator('button').click()
  await expect(page.locator('.point-details h2')).toHaveText(lastName!)
  await page.getByRole('link', { name: /Como chegar/ }).scrollIntoViewIfNeeded()
  const route = await page.getByRole('link', { name: /Como chegar/ }).boundingBox()
  expect(route!.height).toBeGreaterThanOrEqual(44)
  await page.getByRole('button', { name: 'Voltar aos destinos' }).click()
})
